### ISSUE TITLE
Small install howto?

### ISSUE THREAD

**Issue by frekel** [voydz/alexa-lgtv-remote#1]
Can you provide a small howto on installing this (for me a RPi3 ;)?
And what commands we needs to give Alexa?

Thanks,
Frank

**Comment by voydz** [comment]
Sure, I will reach back if I got something written up.

Thanks for your interest, much appreciated :)

**Comment by voydz** [comment]
@frekel Hey there, I finally found the time to write a little [Getting started](https://github.com/voydz/alexa-lgtv-remote#getting-started).
