### ISSUE TITLE
Remote Endpoint Error

### ISSUE THREAD

**Issue by oxhey** [voydz/alexa-lgtv-remote#2]
npm run start works fine.

It says its listening on port 3000!

When I run the simulator on amazon I get this error:
"The remote endpoint could not be called, or the response it returned was invalid."

Under the skill config I have it set to HTTPS / Europe and this in the box https://MYIP

I have made a self signed certificate. I have even tried changing the ip to a domain I own.

Am I doing anything wrong?

**Comment by voydz** [comment]
@oxhey Hey, the project dependencies might be out of date. Causing problems with Alexas current request scheme.

You can try to get the Alexa wrapper working for yourself, as the remote control components should work just fine.

Currently I am lacking a solution to run this tool for myself. As soon as I figured something out, expect this project to be updated. I can give no estimate here.

thanks for your interest in this project :)
greetings
