### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by StarfighterJ** [voydz/alexa-lgtv-remote#4]
First Does this work? Also on Install all dependencies with npm install. what do I install first?, and on  Run the app with npm run start what do I start.
Please help thank you

**Comment by voydz** [comment]
Hi,

1. `npm install` will automatically install all required dependencies on a project level for you. No need to specify anything further.
2. `npm run start` will start the API Gateway (managing a Alexa ASK Endpoint and its connection to the LG webOS Websocket)

Also have a look at the fork at https://github.com/pparedes1/alexa-lgtv-remote. There you will find more detailed guidelines on how to setup this project.

greetings

**Comment by voydz** [comment]
consider this closed due to #5
