### ISSUE TITLE
Another Help

### ISSUE THREAD

**Issue by StarfighterJ** [voydz/alexa-lgtv-remote#5]
Hi and thanks for to info on the other help. I am kinda  new at this I was trying to put this in pparedes1 Issues, but he does not have a Issues tab. I am trying to Put this in AWS Lambda and I am not sure what Files I need  to be Zipped and uploaded there I assume it is all the Files in the SRC Folder. Also not sure on Designer Which Trigger I should use: Alexa Skills Kit, or Alexa Smart Home. If it is Alexa Smart Home. did you have to Discover Device with Alexa?  If you know the answers to his Please help or if you know away to get to pparedes1 that would help also.
Thank you for you time on this

 Also I understand what info to put in this File, but what does this mean? : Configure your environment. First cp .env.example .env, then manipulate the values in .env. was I suppose to change the name of this File?
Here is what i got in the file .env
PORT=3000

TV_SOCKET=XXX.XXX.X.XXX:3000
TV_MAC=XX:XX:XX:XX:XX:XX
  This is what I get after npm run Start:
C:\Users\TEST\Downloads\alexa-lgtv-remote-master (1)\alexa-lgtv-remote-master>npm run start

> alexa-lgtv-remote@1.0.0 start C:\Users\TEST\Downloads\alexa-lgtv-remote-master (1)\alexa-lgtv-remote-master
> gulp build && node dist/index.js

[19:28:41] Using gulpfile ~\Downloads\alexa-lgtv-remote-master (1)\alexa-lgtv-remote-master\gulpfile.js
[19:28:41] Starting 'build'...
[19:28:41] Starting 'lint'...
[19:28:49] Finished 'lint' after 7.87 s
[19:28:49] Starting 'builder'...
[19:28:50] Finished 'builder' after 555 ms
[19:28:50] Finished 'build' after 8.43 s
alexa-lgtv-remote listening on port 3000!
{ Error: getaddrinfo ENOTFOUND 3000 3000:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  message: 'getaddrinfo ENOTFOUND 3000 3000:80',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '3000',
  host: '3000',
  port: 80 }

**Comment by pparedes1** [comment]
Hi, In designer you want to select Custom for the Alexa Skills kit to begin the instructions. I did not deploy on AWS Lambda, but I would first make sure you are working locally before remote deployment. It should be as "simple" as cloning your repository into AWS, configuring the environment variables, and making sure your router points the traffic from that port to the TV. 

I believe in TV_SOCKET you want to prefix the ip address with ws:// (can't remember if voydz code adds that automatically, some of the code I've seen do). Also is your TV turned on the first time you run this? You'll need to pair the tv with this program, it should prompt you on the TV to accept commands from this code the first time your run it.

BTW as a good practice, you might want to consider editing your previous issue and deleting your MAC address from the comment above.

**Comment by voydz** [comment]
Is this still relevant? I think @pparedes1 Readme sheds a lot more light on setting things up. ;)

**Comment by voydz** [comment]
closing as not longer relevant
